In [106]:
import pandas as pd
import numpy as np

print("ML Setup Successful 🚀")

ML Setup Successful 🚀

In [107]:
import pandas as pd

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [108]:
print("Train Shape:", train.shape)
print("Test Shape:", test.shape)

Train Shape: (77299, 11)
Test Shape: (41778, 10)

In [109]:
train.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [110]:
train.columns

Index(['Index', 'geohash', 'day', 'timestamp', 'demand', 'RoadType',
       'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature',
       'Weather'],
      dtype='object')

In [111]:
train.isnull().sum()

Index               0
geohash             0
day                 0
timestamp           0
demand              0
RoadType          600
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      2495
Weather           797
dtype: int64

In [112]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  object
 2   day            77299 non-null  int64
 3   timestamp      77299 non-null  object
 4   demand         77299 non-null  float64
 5   RoadType       76699 non-null  object
 6   NumberofLanes  77299 non-null  int64
 7   LargeVehicles  77299 non-null  object
 8   Landmarks      77299 non-null  object
 9   Temperature    74804 non-null  float64
 10  Weather        76502 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 6.5+ MB

In [113]:
train.describe()

              Index           day        demand  NumberofLanes   Temperature
count  77299.000000  77299.000000  7.729900e+04   77299.000000  74804.000000
mean   38649.000000     48.101838  9.394238e-02       2.014334     16.405354
std    22314.443566      0.302438  1.421905e-01       0.904665      7.359835
min        0.000000     48.000000  6.245650e-07       1.000000    -14.935097
25%    19324.500000     48.000000  1.822723e-02       1.000000     11.430473
50%    38649.000000     48.000000  4.775994e-02       2.000000     16.382587
75%    57973.500000     48.000000  1.085951e-01       3.000000     21.298833
max    77298.000000     49.000000  1.000000e+00       5.000000     48.251433

In [114]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  object
 2   day            77299 non-null  int64
 3   timestamp      77299 non-null  object
 4   demand         77299 non-null  float64
 5   RoadType       76699 non-null  object
 6   NumberofLanes  77299 non-null  int64
 7   LargeVehicles  77299 non-null  object
 8   Landmarks      77299 non-null  object
 9   Temperature    74804 non-null  float64
 10  Weather        76502 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 6.5+ MB

In [115]:
train["day"].unique()

array([48, 49])

In [116]:
train["timestamp"].head(10)

0    0:0
1    0:0
2    0:0
3    0:0
4    0:0
5    0:0
6    0:0
7    0:0
8    0:0
9    0:0
Name: timestamp, dtype: object

In [117]:
train["Weather"].unique()

array([nan, 'Sunny', 'Rainy', 'Foggy', 'Snowy'], dtype=object)

In [118]:
train["RoadType"].unique()

array([nan, 'Residential', 'Street', 'Highway'], dtype=object)

In [119]:
train["RoadType"] = train["RoadType"].fillna("Unknown")
test["RoadType"] = test["RoadType"].fillna("Unknown")

train["Weather"] = train["Weather"].fillna("Unknown")
test["Weather"] = test["Weather"].fillna("Unknown")

train["Temperature"] = train["Temperature"].fillna(
    train["Temperature"].median()
)

test["Temperature"] = test["Temperature"].fillna(
    test["Temperature"].median()
)

In [120]:
train.isnull().sum()

Index            0
geohash          0
day              0
timestamp        0
demand           0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
dtype: int64

In [121]:
train["hour"] = train["timestamp"].str.split(":").str[0].astype(int)
train["minute"] = train["timestamp"].str.split(":").str[1].astype(int)

test["hour"] = test["timestamp"].str.split(":").str[0].astype(int)
test["minute"] = test["timestamp"].str.split(":").str[1].astype(int)

In [122]:
train[["timestamp","hour","minute"]].head(10)

  timestamp  hour  minute
0       0:0     0       0
1       0:0     0       0
2       0:0     0       0
3       0:0     0       0
4       0:0     0       0
5       0:0     0       0
6       0:0     0       0
7       0:0     0       0
8       0:0     0       0
9       0:0     0       0

In [123]:
train.select_dtypes(include="object").columns

Index(['geohash', 'timestamp', 'RoadType', 'LargeVehicles', 'Landmarks',
       'Weather'],
      dtype='object')

In [124]:
train["LargeVehicles"].unique()

array(['Not Allowed', 'Allowed'], dtype=object)

In [125]:
train["Landmarks"].unique()

array(['No', 'Yes'], dtype=object)

In [126]:
train["geohash"].nunique()

1249

In [127]:
from sklearn.preprocessing import LabelEncoder

In [128]:
cat_cols = [
    "geohash",
    "RoadType",
    "LargeVehicles",
    "Landmarks",
    "Weather"
]

for col in cat_cols:

    le = LabelEncoder()

    combined = pd.concat([
        train[col],
        test[col]
    ])

    le.fit(combined)

    train[col] = le.transform(train[col])

    test[col] = le.transform(test[col])

In [129]:
train.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,hour,minute
0,0,4,48,0:0,0.048804,3,1,1,0,16.382587,4,0,0
1,1,25,48,0:0,0.118507,1,3,0,1,31.104565,3,0,0
2,2,370,48,0:0,0.027132,1,1,1,0,25.919267,3,0,0
3,3,418,48,0:0,0.003272,1,1,1,0,16.382587,1,0,0
4,4,22,48,0:0,0.010819,1,1,1,0,10.803667,1,0,0

In [130]:
train = train.drop("timestamp", axis=1)
test = test.drop("timestamp", axis=1)

In [131]:
train.head()

,Index,geohash,day,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,hour,minute
0,0,4,48,0.048804,3,1,1,0,16.382587,4,0,0
1,1,25,48,0.118507,1,3,0,1,31.104565,3,0,0
2,2,370,48,0.027132,1,1,1,0,25.919267,3,0,0
3,3,418,48,0.003272,1,1,1,0,16.382587,1,0,0
4,4,22,48,0.010819,1,1,1,0,10.803667,1,0,0

In [132]:
X = train.drop("demand", axis=1)

y = train["demand"]

In [133]:
train.head()

,Index,geohash,day,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,hour,minute
0,0,4,48,0.048804,3,1,1,0,16.382587,4,0,0
1,1,25,48,0.118507,1,3,0,1,31.104565,3,0,0
2,2,370,48,0.027132,1,1,1,0,25.919267,3,0,0
3,3,418,48,0.003272,1,1,1,0,16.382587,1,0,0
4,4,22,48,0.010819,1,1,1,0,10.803667,1,0,0

In [134]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [135]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [136]:
pred = model.predict(X_val)

In [137]:
from sklearn.metrics import r2_score

score = r2_score(y_val, pred)

print("R2 Score =", score)
print("Competition Score =", score * 100)

R2 Score = 0.9425927067188404
Competition Score = 94.25927067188404

In [138]:
pip install catboost

Requirement already satisfied: catboost in c:\users\smrit\anaconda3\lib\site-packages (1.2.10)
Requirement already satisfied: graphviz in c:\users\smrit\anaconda3\lib\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in c:\users\smrit\anaconda3\lib\site-packages (from catboost) (3.10.6)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\smrit\anaconda3\lib\site-packages (from catboost) (2.3.5)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\smrit\anaconda3\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in c:\users\smrit\anaconda3\lib\site-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in c:\users\smrit\anaconda3\lib\site-packages (from catboost) (6.3.0)
Requirement already satisfied: six in c:\users\smrit\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\smrit\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\smrit\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\smrit\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\smrit\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\smrit\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\smrit\anaconda3\lib\site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\smrit\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\smrit\anaconda3\lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\smrit\anaconda3\lib\site-packages (from matplotlib->catboost) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\smrit\anaconda3\lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\smrit\anaconda3\lib\site-packages (from plotly->catboost) (2.7.0)
Note: you may need to restart the kernel to use updated packages.

In [139]:
X.columns

Index(['Index', 'geohash', 'day', 'RoadType', 'NumberofLanes', 'LargeVehicles',
       'Landmarks', 'Temperature', 'Weather', 'hour', 'minute'],
      dtype='object')

In [140]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance.sort_values(
    by="Importance",
    ascending=False
)

          Feature  Importance
3        RoadType    0.747695
1         geohash    0.162003
0           Index    0.037541
9            hour    0.021745
7     Temperature    0.015709
4   NumberofLanes    0.005862
10         minute    0.003846
8         Weather    0.002802
6       Landmarks    0.001354
5   LargeVehicles    0.000832
2             day    0.000611

In [141]:
X = train.drop(["demand", "Index"], axis=1)
y = train["demand"]

In [142]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [143]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [144]:
pred = model.predict(X_val)

from sklearn.metrics import r2_score

score = r2_score(y_val, pred)

print(score)
print(score * 100)

0.9419820959894587
94.19820959894587

In [145]:
from catboost import CatBoostRegressor

In [146]:
cat_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    loss_function='RMSE',
    verbose=100
)

cat_model.fit(X_train, y_train)

0:	learn: 0.1368781	total: 19.9ms	remaining: 19.8s
100:	learn: 0.0618965	total: 1.48s	remaining: 13.2s
200:	learn: 0.0583839	total: 2.63s	remaining: 10.5s
300:	learn: 0.0560228	total: 3.68s	remaining: 8.55s
400:	learn: 0.0540880	total: 4.71s	remaining: 7.03s
500:	learn: 0.0526298	total: 5.8s	remaining: 5.78s
600:	learn: 0.0514787	total: 6.87s	remaining: 4.56s
700:	learn: 0.0505159	total: 8.06s	remaining: 3.44s
800:	learn: 0.0497416	total: 9.28s	remaining: 2.31s
900:	learn: 0.0490874	total: 10.5s	remaining: 1.16s
999:	learn: 0.0484729	total: 11.8s	remaining: 0us

CatBoostRegressor(depth=8, iterations=1000, learning_rate=0.05, loss_function='RMSE', verbose=100)

In [147]:
cat_pred = cat_model.predict(X_val)

In [148]:
from sklearn.metrics import r2_score

cat_score = r2_score(y_val, cat_pred)

print("CatBoost R2 =", cat_score)
print("CatBoost Competition Score =", cat_score * 100)

CatBoost R2 = 0.8633470997333115
CatBoost Competition Score = 86.33470997333114

In [149]:
train["hour"].nunique()

24

In [150]:
train["minute"].nunique()

4

In [151]:
train["hour"].value_counts().sort_index()

hour
0     6338
1     6871
2     4455
3     3595
4     3683
5     3621
6     3665
7     3569
8     3507
9     3549
10    3622
11    3567
12    3525
13    3271
14    3000
15    2580
16    2108
17    1684
18    1247
19    1214
20    1418
21    1738
22    2410
23    3062
Name: count, dtype: int64

In [152]:
test = test.drop("timestamp", axis=1)

KeyError: "['timestamp'] not found in axis"

In [ ]:
test_pred = model.predict(test)

In [ ]:
X_train.shape

In [ ]:
test.shape

In [ ]:
set(X_train.columns) - set(test.columns)

In [ ]:
set(test.columns) - set(X_train.columns)

In [ ]:
test_index = test["Index"]

In [ ]:
test_model = test.drop("Index", axis=1)

In [ ]:
print(test_model.shape)

In [ ]:
test_pred = model.predict(test_model)

In [ ]:
submission = pd.DataFrame({
    "Index": test_index,
    "demand": test_pred
})

submission.head()

In [ ]:
submission.to_csv("submission.csv", index=False)

In [ ]:
submission.shape

In [ ]:
submission.head()

In [ ]:
train["day"].value_counts()

In [ ]:
train_day48 = train[train["day"] == 48]
val_day49 = train[train["day"] == 49]

X_train2 = train_day48.drop("demand", axis=1)
y_train2 = train_day48["demand"]

X_val2 = val_day49.drop("demand", axis=1)
y_val2 = val_day49["demand"]

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model2 = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model2.fit(X_train2, y_train2)

In [ ]:
from sklearn.metrics import r2_score

pred2 = model2.predict(X_val2)

score2 = r2_score(y_val2, pred2)

print(score2)
print(score2 * 100)

In [ ]:
train["rush_hour"] = train["hour"].isin(
    [7,8,9,17,18,19]
).astype(int)

test["rush_hour"] = test["hour"].isin(
    [7,8,9,17,18,19]
).astype(int)

In [ ]:
train["is_night"] = train["hour"].isin(
    [0,1,2,3,4,5]
).astype(int)

test["is_night"] = test["hour"].isin(
    [0,1,2,3,4,5]
).astype(int)

In [ ]:
train.groupby("hour")["demand"].mean()

In [ ]:
pip install lightgbm

In [ ]:
train["peak_hour"] = train["hour"].isin(
    [10,11,12,13]
).astype(int)

test["peak_hour"] = test["hour"].isin(
    [10,11,12,13]
).astype(int)

In [ ]:
train.groupby("geohash")["demand"].mean().describe()

In [ ]:
train.groupby("RoadType")["demand"].mean()

In [ ]:
from lightgbm import LGBMRegressor

In [ ]:
from lightgbm import LGBMRegressor

lgb_model = LGBMRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=8,
    num_leaves=31,
    random_state=42
)

lgb_model.fit(X_train, y_train)

lgb_pred = lgb_model.predict(X_val)

from sklearn.metrics import r2_score

lgb_score = r2_score(y_val, lgb_pred)

print("LightGBM R2 =", lgb_score)
print("Competition Score =", lgb_score * 100)

In [ ]:
train.groupby("RoadType")["demand"].mean()

In [ ]:
train.groupby("Weather")["demand"].mean()

In [ ]:
geo_mean = train.groupby("geohash")["demand"].mean()

train["geo_demand"] = train["geohash"].map(geo_mean)

test["geo_demand"] = test["geohash"].map(geo_mean)

In [ ]:
train[["geohash","geo_demand"]].head()

In [ ]:
X = train.drop("demand", axis=1)
y = train["demand"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import r2_score

pred = model.predict(X_val)

score = r2_score(y_val, pred)

print("R2 =", score)
print("Competition Score =", score * 100)

In [ ]:
test_pred = model.predict(test)

submission = pd.DataFrame({
    "Index": test["Index"],
    "demand": test_pred
})

submission.to_csv("submission_v2.csv", index=False)

In [ ]:
importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": model.feature_importances_
}).sort_values("Importance", ascending=False)

importance

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=500,
    max_depth=20,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor

model = ExtraTreesRegressor(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor

model = ExtraTreesRegressor(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

pred = model.predict(X_val)

from sklearn.metrics import r2_score

score = r2_score(y_val, pred)

print("R2 =", score)
print("Competition Score =", score*100)

In [ ]:
test_pred = model.predict(test)

In [ ]:
test_pred = model.predict(test)

submission = pd.DataFrame({
    "Index": test["Index"],
    "demand": test_pred
})

submission.to_csv("submission_v3.csv", index=False)

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor

model = ExtraTreesRegressor(
    n_estimators=1000,
    max_depth=20,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

In [ ]:
importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": model.feature_importances_
}).sort_values("Importance", ascending=False)

print(importance)

In [153]:
importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": model.feature_importances_
}).sort_values("Importance", ascending=False)

print(importance)

         Feature  Importance
2       RoadType    0.747695
0        geohash    0.163886
8           hour    0.045339
6    Temperature    0.020046
3  NumberofLanes    0.006641
9         minute    0.005908
1            day    0.004155
7        Weather    0.003607
5      Landmarks    0.001764
4  LargeVehicles    0.000958

In [154]:
model.fit(X, y)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [157]:
test_pred = model.predict(test)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Index

In [156]:
test_final = test[X.columns]
test_pred = model.predict(test_final)

In [158]:
test_pred = model.predict(test)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Index

In [159]:
print(X.columns.tolist())
print(test.columns.tolist())

['geohash', 'day', 'RoadType', 'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature', 'Weather', 'hour', 'minute']
['Index', 'geohash', 'day', 'RoadType', 'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature', 'Weather', 'hour', 'minute']

In [160]:
test_pred = model.predict(test.drop(columns=["Index"]))

In [161]:
test_pred = model.predict(test)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Index

In [162]:
print(test.drop(columns=["Index"]).isnull().sum())

geohash          0
day              0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
hour             0
minute           0
dtype: int64

In [163]:
test_pred = model.predict(test.drop(columns=["Index"]))

In [164]:
submission = pd.DataFrame({
    "Index": test["Index"],
    "demand": test_pred
})

In [165]:
submission.head()

   Index    demand
0      0  0.110159
1      1  0.022469
2      2  0.031259
3      3  0.030489
4      4  0.052611

In [166]:
submission.to_csv("submission_v4.csv", index=False)

In [167]:
model = RandomForestRegressor(
    n_estimators=500,
    max_depth=15,
    min_samples_leaf=3,
    min_samples_split=10,
    random_state=42,
    n_jobs=-1
)

In [168]:
model.fit(X_train, y_train)

pred = model.predict(X_val)

from sklearn.metrics import r2_score

score = r2_score(y_val, pred)

print("R2 =", score)
print("Competition Score =", score*100)

R2 = 0.9222763298868103
Competition Score = 92.22763298868102

In [169]:
submission.to_csv("submission_v5.csv", index=False)

In [170]:
from sklearn.ensemble import ExtraTreesRegressor

model = ExtraTreesRegressor(
    n_estimators=1000,
    max_depth=20,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

In [171]:
model.fit(X_train, y_train)

pred = model.predict(X_val)

from sklearn.metrics import r2_score

score = r2_score(y_val, pred)

print("R2 =", score)
print("Competition Score =", score*100)

R2 = 0.8865595932661767
Competition Score = 88.65595932661768

In [172]:
final_pred = 0.3 * rf_pred + 0.7 * extra_pred

NameError: name 'rf_pred' is not defined